### ISSUE TITLE
Not working properly 

### ISSUE THREAD

**Issue by umarsalman** [umarsalman/Weather-Scrapper#1]
Here I am using data from another website to dispaly in my web app. Earlier it was working fine but now it shows some error.

**Comment by GregHolmes** [comment]
I've corrected the issue with the scraping. I would advise that maybe you change this process though. It would be easier and more manageable if you were to use an API (There are several out there), which would mean you wouldn't be relying on the website weather-forecast.com not updating the styling of their website.

https://github.com/umarsalman/Weather-Scrapper/pull/3
